# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('add_goal', '0002_auto_20160630_1506'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='milestone',
            managers=[
                ('milestoneManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='milestone',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='reoccuring',
            field=models.BooleanField(default=False),
        ),
    ]
