# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:18
from __future__ import unicode_literals

import apps.login_reg_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, validators=[apps.login_reg_app.models.validate_lengthGreaterThanTwo]),
        ),
    ]
