# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 03:25
from __future__ import unicode_literals

import apps.login_reg_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20160622_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, validators=[apps.login_reg_app.models.validate_lengthGreaterThanTwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, validators=[apps.login_reg_app.models.validate_password]),
        ),
    ]
