# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0003_auto_20160626_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
